### PR TITLE
Team 4: remove user id from organizations

### PR DESCRIPTION
**Pull request by ghost**
Removed user_id from organizations table. Team 5 please review.

### CODE REVIEW

**Comment by tkbeili** [comment]
You should remove the `belongs_to` in the `organization.rb`

Also, make sure that all the specs are passing, there will likely be broken specs.

**Comment by ffoger** [comment]
Will do. Thanks Tam.

**Comment by ghost** [comment]
Tam, we did review this with Steve and there was no belongs_to in the organization.rb. There's a relationship between User and Organization which is one user belongs to one organization. We'll write a unit test to validate the changes we worked on yesterday.

**Comment by tkbeili** [comment]
@ffoger can you please rebase on top of integration? I will read the code again after that.

**Pull request closed without merging**
